ifndef::imagesDir[]
:imagesDir: images
endif::[]

[[admincmds]]
== Administrative Commands

[[admincmds-systs]]
=== System Status
Query current live status of system.

_Response Properties_

[1,1,1]
|===
| Path | Type |Description

| id	| Text	| Venue short name
| name	| Text	| Venue full name
| startTime	| Text	| Time when the instance started
| version	| Text	| Version of MktSimulator

|=== 

[[admincmds-systs-get]]
==== Get System Status
Request system status.

_Resource URI_
----
GET /api/status
----

_Example_: Request system status

[,http]
----
GET /api/status HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost
----

_Example_: Possible reply

[,http]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "id" : "LSE",
    "name": "London Stock Exchange",
    "startTime":"2022-Feb-03 12:16:50"
    "version" : "99.116.15829062-734713bc (28/02/2020 17:40:18)"
}
----

[[admincmds-vensts]]
=== Venue Status
Manage current live status of each market simulator venue instance.

_Response Properties_

[1,1,1]
|===
| Path | Type |Description

| id	| Text	| Venue short name
| name	| Text	| Venue full name
| startTime	| Text	| Time when the instance started
| version	| Text	| Version of MktSimulator
| responseCode	| Integer	| HTTP code received in response to venue status request
|===

[[admincmds-vensts-getsgl]]
==== Get Single Venue Status
Request the status of a single market simulator venue instance.

_Resource URI_

----
GET /api/venuestatus/{venueId}
----

_Example_: Request single venue status

[,http]
----
GET /api/venuestatus/LSE HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost
----

_Example_: Possible reply

[,http]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "id" : "LSE",
    "name": "London Stock Exchange",
    "startTime":"2022-Feb-03 12:16:50"
    "version" : "99.116.15829062-734713bc (28/02/2020 17:40:18)"
    "statusCode" : 200
}
----

[[admincmds-vensts-getmultil]]
==== Get Multiple Venue Status
Request the status of all market simulator venue instances.

_Resource URI_

----
GET /api/venuestatus
----

_Example_: Request single venue status

[,http]
----
GET /api/venuestatus HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost
----

_Example_: Possible reply

[,http]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "venuestatus": [
        {
            "id":"FASTMATCH",
            "name":"FASTMATCH",
            "startTime":"2023-Feb-09 09:34:42.216182",
            "version":"develop.3.1675934598-87a7b61c(2023-02-09 11:23:18 +0200)",
            "statusCode":200
        },
        {
            "id":"XETRA",
            "name":"XETRA",
            "startTime":"2023-Feb-09 09:34:42.216182",
            "version":"develop.3.1675934598-87a7b61c(2023-02-09 11:23:18 +0200)",
            "statusCode":200
        },
        {
            "id":"BSE",
            "name":"BSE",
            "startTime":"2023-Aug-07 11:28:19.623110",
            "version":"3.1691404393_9ee00fc9(2023-08-07 13:33:13 +0300)",
            "statusCode":503
        }
    ]
}
----

[[admincmds-ordergen]]
=== Order Generation
Manage current status of random order generation and historical data playback of each market simulator venue instance.

_Response Properties_

[1,1,1]
|===
| Path | Type |Description

| result | Text | Explanation of HTTP code received in response to request
|===

[[admincmds-ordergen-sts]]
==== Status of Order Generation
Request the status of random order generation and historical data playback for a single market simulator venue instance.

_Resource URI_

----
GET /api/genstatus/{venueId}
----

_Example_: Request for status of generation for a single instance

[,http]
----
GET /api/genstatus/LSE HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost
----

_Example_: Reply in case the generation is running

[,http]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "result" : "Running"
}
----

_Example_: Reply in case the generation is not running

[,http]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "result" : "NotRunning"
}
----

_Example_: Reply in case a venue does not exist

[,http]
----
HTTP/1.1 502 Bad Gateway
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "result" : "Could not resolve destination instance with AAAAA identifier"
}
----

[[admincmds-ordergen-startstop]]
==== Start/Stop Order Generation
Start or stop random order generation and historical data playback for a single market simulator venue instance.

_Resource URI_

----
POST /api/[genstart|genstop]/{venueId}
----

_Example_: Request to start generation for a single venue

[,http]
----
POST /api/genstart/XETRA HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost
----

_Example_: Possible reply

[,http]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "result" : "Random orders generator started successfully"
}
----

_Example_: Request to stop generation for a single instance

[,http]
----
POST /api/genstop/XETRA HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost
----

_Example_: Possible reply

[,http]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "result" : "Random orders generator stopped successfully"
}
----

[[admincmds-mktphshalt]]
=== Market Phase Halt
Manage halted status of current market phase of each market simulator venue instance. See <<general-mktphs,this section>> for more information about market phases.

_Response Properties_

[1,1,1]
|===
| Path | Type |Description

| result | Text | Explanation of HTTP code received in response to request
|===

[[admincmds-mktphshalt-haltresume]]
==== Halt/Resume Market Phase
Halt or resume current market phase for a single market simulator venue instance.

_Request Properties_

[cols="25,15,60"]
|===
| Path | Type |Description

| allowCancels | Boolean a| Defines whether order cancellation by OrderCancelRequest (35=F) is allowed during the Open Halted phase. Used only when halting current market phase.

*	`true` - OrderCancelRequest (35=F) can be processed. 
If the order is cancelled, the market simulator's response is ExecutionReport (35=8), in which OrdStatus is Canceled (39=4).
*	`false` - OrderCancelRequest (35=F) will be rejected - orders cannot be cancelled. 
The market simulator's response is OrderCancelReject (35=9), in which OrdStatus is Rejected (39=8).
|===

_Resource URI_

----
POST /api/[halt|resume]/{venueId}
----

_Example_: Halt market for a single venue

[,http]
----
POST /api/halt/LSE HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost

{
    "allowCancels": false
}
----

_Example_: Positive reply

[,http]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "result" : "Market successfully halted"
}
----

_Example_: Reply if the phase is already halted

[,http]
----
HTTP/1.1 409 Conflict
Connection: Close
Content-Length: XXX

{
    "result" : "The market is already halted."
}
----

_Example_: Reply if there is no active phase

[,http]
----
HTTP/1.1 404 Not Found
Connection: Close
Content-Length: XXX

{
    "result" : "There is no phase to halt."
}
----

_Example_: If the current phase cannot be halted

[,http]
----
HTTP/1.1 409 Conflict
Connection: Close
Content-Length: XXX

{
    "result" : "Unable to halt the phase."
}
----

_Example_: Resume market for a single venue

[,http]
----
POST /api/resume/LSE HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost
----

_Example_: Positive reply

[,http]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "result" : "The market was successfully resumed."
}
----

_Example_: Reply if the phase is not currently halted

[,http]
----
HTTP/1.1 409 Conflict
Connection: Close
Content-Length: XXX

{
    "result" : "There is no halt request to terminate."
}
----

[[admincmds-simstate]]
=== Market Simulator State
Manage the current state of traded market listings and settings for each market simulator venue instance.

_Response Properties_

[1,1,1]
|===
| Path | Type |Description

| result | Text | Explanation of HTTP code received in response to request
|===

[[admincmds-simstate-storerecover]]
==== Store/Recover Market State For Single Venue
Store or recover current market state of traded listings for a single market simulator venue instance with a persisted state file. This includes only the live market state of each traded listing, not the configured settings from the database. See <<general-persiststate,this section>> for more information about persisted market state.

Store or recover market state for current market simulator venue with configured persisted state file.

_Resource URI_

----
POST /api/[store|recover]
----

Store or recover market state for specific market simulator venue with configured persisted state file.

_Resource URI_

----
POST /api/[store|recover]/{venueId}
----

_Example_: Store market state for current venue

[,http]
----
POST /api/store HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost
----

_Example_: Positive reply

[,http]
----
HTTP/1.1 201 Created
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "result": "Matching engine state has been successfully persisted." 
}
----

_Example_: Store market state for a specific venue

[,http]
----
POST /api/store/LSE HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost
----

_Example_: Positive reply

[,http]
----
HTTP/1.1 201 Created
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "result": "Matching engine state has been successfully persisted." 
}
----

_Example_: Recover market state for current venue

[,http]
----
POST /api/recover HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost
----

_Example_: Positive reply

[,http]
----
HTTP/1.1 201 Created
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "result" : "Matching engine state has been successfully recovered"
}
----

_Example_: Recover market state for a specific venue

[,http]
----
POST /api/recover/LSE HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost
----

_Example_: Positive reply

[,http]
----
HTTP/1.1 201 Created
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "result" : "Matching engine state has been successfully recovered"
}
----

[[admincmds-simstate-reset]]
==== Reset Configured State For Single Venue

Reset configured initial state for a single market simulator venue instance from database settings. All simulator settings will be refreshed from the database. If the venue is configured with persistenceEnabled = true, like a normal simulator startup sequence, the listings specified in the configured persistence file path for that venue will have their market state restored, and any other active traded listings will have their market states cleared. Random order generation and historical data playback will also be stopped, and only restarted if the venue is configured with orderOnStartup = true. The REST and FIX engines will also be reset during this time, causing active connections to be disrupted.

The simulator XML file configuration and FIX file configuration will not be reloaded during a reset. A physical restart of the market simulator process is required to reload these settings.

NOTE: Changing the venueId of the venue associated with the simulator instance or the configured restPort for a live running market simulator instance before resetting the configured state is not supported and will likely have unstable results.

Reset configured state for current market simulator venue.

_Resource URI_

----
POST /api/reset
----

Reset configured state for a specific market simulator venue.

_Resource URI_

----
POST /api/reset/{venueId}
----

_Example_: Reset configured state for current venue

[,http]
----
POST /api/reset HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost
----

_Example_: Positive reply

[,http]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "result" : "Resetting the venue state starts."
}
----

_Example_: Reset configured state for a specific venue

[,http]
----
POST /api/reset/LSE HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost
----

_Example_: Positive reply

[,http]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "result" : "Resetting the venue state starts."
}
----
