ifndef::imagesDir[]
:imagesDir: images
endif::[]

[[admincmds]]
== Administrative Commands

[[admincmds-vensts]]
=== Venue Status
Manage current live status of each market simulator venue instance.

_Response Properties_

[1,1,1]
|===
| Path | Type | Description

| id | Text | Venue short name
| name | Text | Venue full name
| startTime | Text | Time when the instance started
| version | Text | Version of MktSimulator
| sessionSettings | Array | QuickFIX session settings configured for this venue instance, as parsed by the venue
| statusCode | Integer | HTTP code received in response to venue status request
|===

_Session Settings Sub-List_

[1,1,1]
|===
| Path | Type | Description

| section | Text | Section name (e.g. `DEFAULT` or `SESSION`)
| id | Text | Session identifier in the format `+{BeginString}:{SenderCompID}->{TargetCompID}+` — only present for `SESSION` sections
| settings | Object | Key-value pairs of settings for the section; `SESSION` sections contain only session-specific settings, excluding common `DEFAULT` settings

|===

[[admincmds-vensts-getsgl]]
==== Get Single Venue Status
Request the status of the current market simulator venue instance.

_Resource URI_

----
GET /api/venuestatus
----

Request the status of a specific market simulator venue instance.

_Resource URI_

----
GET /api/venuestatus/{venueId}
----

_Example_: Request current venue status

[,http]
----
GET /api/venuestatus HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost
----

_Example_: Possible reply

[,http]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
  "id": "LSE",
  "name": "LondonStockExchange",
  "startTime": "2026-Mar-19 16:54:48.874227",
  "version": "unversioned.1773921825_8f0c76bf(2026-03-19 12:03:45 +0000)",
  "sessionSettings": [
    {
      "section": "DEFAULT",
      "settings": {
        "ALLOWUNKNOWNMSGFIELDS": "Y",
        "APPDATADICTIONARY": "/cfg/default/FIX50SP2_marketsimulator.xml",
        "CHECKLATENCY": "N",
        "CONNECTIONTYPE": "acceptor",
        "ENDTIME": "00:00:00",
        "FILESTOREPATH": "/quickfix_persistence",
        "HEARTBTINT": "600",
        "LOGOUTTIMEOUT": "30",
        "SOCKETACCEPTPORT": "9001",
        "SOCKETNODELAY": "Y",
        "SOCKETREUSEADDRESS": "Y",
        "STARTTIME": "00:00:00",
        "TRANSPORTDATADICTIONARY": "/cfg/default/FIXT11_marketsimulator.xml",
        "VALIDATEUSERDEFINEDFIELDS": "N"
      }
    },
    {
      "section": "SESSION",
      "id": "FIXT.1.1:MktSimulator->QuodFeedhandler",
      "settings": {
        "BEGINSTRING": "FIXT.1.1",
        "DEFAULTAPPLVERID": "9",
        "PERSISTMESSAGES": "N",
        "RESETONLOGON": "Y",
        "SENDERCOMPID": "MktSimulator",
        "TARGETCOMPID": "QuodFeedhandler"
      }
    },
    {
      "section": "SESSION",
      "id": "FIXT.1.1:MktSimulator->QuodGateway",
      "settings": {
        "BEGINSTRING": "FIXT.1.1",
        "DEFAULTAPPLVERID": "9",
        "MILLISECONDSINTIMESTAMP": "Y",
        "PERSISTMESSAGES": "Y",
        "REFRESHONLOGON": "Y",
        "RESETONLOGON": "N",
        "SENDERCOMPID": "MktSimulator",
        "TARGETCOMPID": "QuodGateway",
        "TIMESTAMPPRECISION": "5"
      }
    }
  ],
  "statusCode": 200
}
----

_Example_: Request specific venue status

[,http]
----
GET /api/venuestatus/LSE HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost
----

_Example_: Possible reply

[,http]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
  "id": "LSE",
  "name": "LondonStockExchange",
  "startTime": "2026-Mar-19 16:54:48.874227",
  "version": "unversioned.1773921825_8f0c76bf(2026-03-19 12:03:45 +0000)",
  "sessionSettings": [
    {
      "section": "DEFAULT",
      "settings": {
        "ALLOWUNKNOWNMSGFIELDS": "Y",
        "APPDATADICTIONARY": "/cfg/default/FIX50SP2_marketsimulator.xml",
        "CHECKLATENCY": "N",
        "CONNECTIONTYPE": "acceptor",
        "ENDTIME": "00:00:00",
        "FILESTOREPATH": "/quickfix_persistence",
        "HEARTBTINT": "600",
        "LOGOUTTIMEOUT": "30",
        "SOCKETACCEPTPORT": "9001",
        "SOCKETNODELAY": "Y",
        "SOCKETREUSEADDRESS": "Y",
        "STARTTIME": "00:00:00",
        "TRANSPORTDATADICTIONARY": "/cfg/default/FIXT11_marketsimulator.xml",
        "VALIDATEUSERDEFINEDFIELDS": "N"
      }
    },
    {
      "section": "SESSION",
      "id": "FIXT.1.1:MktSimulator->QuodFeedhandler",
      "settings": {
        "BEGINSTRING": "FIXT.1.1",
        "DEFAULTAPPLVERID": "9",
        "PERSISTMESSAGES": "N",
        "RESETONLOGON": "Y",
        "SENDERCOMPID": "MktSimulator",
        "TARGETCOMPID": "QuodFeedhandler"
      }
    },
    {
      "section": "SESSION",
      "id": "FIXT.1.1:MktSimulator->QuodGateway",
      "settings": {
        "BEGINSTRING": "FIXT.1.1",
        "DEFAULTAPPLVERID": "9",
        "MILLISECONDSINTIMESTAMP": "Y",
        "PERSISTMESSAGES": "Y",
        "REFRESHONLOGON": "Y",
        "RESETONLOGON": "N",
        "SENDERCOMPID": "MktSimulator",
        "TARGETCOMPID": "QuodGateway",
        "TIMESTAMPPRECISION": "5"
      }
    }
  ],
  "statusCode": 200
}
----

[[admincmds-vensts-getmultil]]
==== Get Multiple Venue Status
Request the status of all market simulator venue instances.

_Resource URI_

----
GET /api/allvenuestatus
----

_Example_: Request all venues' status

[,http]
----
GET /api/allvenuestatus HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost
----

_Example_: Possible reply

[,http]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
  "venuestatus": [
    {
      "id": "LSE",
      "name": "LondonStockExchange",
      "startTime": "2026-Mar-19 16:54:48.874227",
      "version": "unversioned.1773921825_8f0c76bf(2026-03-19 12:03:45 +0000)",
      "sessionSettings": [
        {
          "section": "DEFAULT",
          "settings": {
            "ALLOWUNKNOWNMSGFIELDS": "Y",
            "APPDATADICTIONARY": "/cfg/default/FIX50SP2_marketsimulator.xml",
            "CHECKLATENCY": "N",
            "CONNECTIONTYPE": "acceptor",
            "ENDTIME": "00:00:00",
            "FILESTOREPATH": "/quickfix_persistence",
            "HEARTBTINT": "600",
            "LOGOUTTIMEOUT": "30",
            "SOCKETACCEPTPORT": "9001",
            "SOCKETNODELAY": "Y",
            "SOCKETREUSEADDRESS": "Y",
            "STARTTIME": "00:00:00",
            "TRANSPORTDATADICTIONARY": "/cfg/default/FIXT11_marketsimulator.xml",
            "VALIDATEUSERDEFINEDFIELDS": "N"
          }
        },
        {
          "section": "SESSION",
          "id": "FIXT.1.1:MktSimulator->QuodFeedhandler",
          "settings": {
            "BEGINSTRING": "FIXT.1.1",
            "DEFAULTAPPLVERID": "9",
            "PERSISTMESSAGES": "N",
            "RESETONLOGON": "Y",
            "SENDERCOMPID": "MktSimulator",
            "TARGETCOMPID": "QuodFeedhandler"
          }
        },
        {
          "section": "SESSION",
          "id": "FIXT.1.1:MktSimulator->QuodGateway",
          "settings": {
            "BEGINSTRING": "FIXT.1.1",
            "DEFAULTAPPLVERID": "9",
            "MILLISECONDSINTIMESTAMP": "Y",
            "PERSISTMESSAGES": "Y",
            "REFRESHONLOGON": "Y",
            "RESETONLOGON": "N",
            "SENDERCOMPID": "MktSimulator",
            "TARGETCOMPID": "QuodGateway",
            "TIMESTAMPPRECISION": "5"
          }
        }
      ],
      "statusCode": 200
    },
    {
      "id": "XETRA",
      "name": "XETRA",
      "startTime": "2026-Mar-19 15:01:58.096831",
      "version": "unversioned.1773921825_8f0c76bf(2026-03-19 12:03:45 +0000)",
      "sessionSettings": [
        {
          "section": "DEFAULT",
          "settings": {
            "ALLOWUNKNOWNMSGFIELDS": "Y",
            "APPDATADICTIONARY": "/market-simulator/quod/cfg/default/FIX50SP2_marketsimulator.xml",
            "CHECKLATENCY": "N",
            "CONNECTIONTYPE": "acceptor",
            "ENDTIME": "00:00:00",
            "FILESTOREPATH": "/quickfix_persistence",
            "HEARTBTINT": "600",
            "LOGOUTTIMEOUT": "30",
            "SOCKETACCEPTPORT": "9051",
            "SOCKETNODELAY": "Y",
            "SOCKETREUSEADDRESS": "Y",
            "STARTTIME": "00:00:00",
            "TRANSPORTDATADICTIONARY": "/market-simulator/quod/cfg/default/FIXT11_marketsimulator.xml",
            "VALIDATEUSERDEFINEDFIELDS": "N"
          }
        },
        {
          "section": "SESSION",
          "id": "FIXT.1.1:MktSimulator->QuodFeedhandler",
          "settings": {
            "BEGINSTRING": "FIXT.1.1",
            "DEFAULTAPPLVERID": "9",
            "PERSISTMESSAGES": "N",
            "RESETONLOGON": "Y",
            "SENDERCOMPID": "MktSimulator",
            "TARGETCOMPID": "QuodFeedhandler"
          }
        },
        {
          "section": "SESSION",
          "id": "FIXT.1.1:MktSimulator->QuodGateway",
          "settings": {
            "BEGINSTRING": "FIXT.1.1",
            "DEFAULTAPPLVERID": "9",
            "MILLISECONDSINTIMESTAMP": "Y",
            "PERSISTMESSAGES": "N",
            "REFRESHONLOGON": "Y",
            "RESETONLOGON": "N",
            "SENDERCOMPID": "MktSimulator",
            "TARGETCOMPID": "QuodGateway",
            "TIMESTAMPPRECISION": "5"
          }
        }
      ],
      "statusCode": 200
    },
    {
      "id": "FASTMATCH",
      "name": "FASTMATCH",
      "statusCode": 502
    }
  ]
}
----

[[admincmds-ordergen]]
=== Order Generation
Manage current status of random order generation and historical data playback of each market simulator venue instance.

_Response Properties_

[1,1,1]
|===
| Path | Type |Description

| result | Text | Explanation of HTTP code received in response to request
|===

[[admincmds-ordergen-sts]]
==== Status of Order Generation
Request the status of random order generation and historical data playback for the current market simulator venue instance.

_Resource URI_

----
GET /api/genstatus
----

Request the status of random order generation and historical data playback for a specific market simulator venue instance.

_Resource URI_

----
GET /api/genstatus/{venueId}
----

_Example_: Request for status of generation for the current instance

[,http]
----
GET /api/genstatus HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost
----

_Example_: Reply in case the generation is running

[,http]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "result" : "Running"
}
----

_Example_: Reply in case the generation is not running

[,http]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "result" : "NotRunning"
}
----

_Example_: Request for status of generation for a specific instance

[,http]
----
GET /api/genstatus/LSE HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost
----

_Example_: Reply in case the generation is running

[,http]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "result" : "Running"
}
----

_Example_: Reply in case the generation is not running

[,http]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "result" : "NotRunning"
}
----

_Example_: Reply in case a venue does not exist

[,http]
----
HTTP/1.1 502 Bad Gateway
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "result" : "Could not resolve destination instance with AAAAA identifier"
}
----

[[admincmds-ordergen-startstop]]
==== Start/Stop Order Generation
Start or stop random order generation and historical data playback for a single market simulator venue instance.

_Request Properties_

[cols="1,1,1"]
|===
| Path | Type | Description

| seed
| String
a| Optional static seed that can be used to override the default random seed value used for the random order generator in order to produce deterministic results on each separate run of the market simulator instance. Used only with genstart.

* Any string value is valid, e.g. `42`, `hello`, `-1`. The provided static seed is combined with an internal hard-coded value using a hash function in order to maintain strong random properties for the initial seed.
* If the value is missing or set to null, the default random seed for order generation will be used, and results will be non-deterministic on each separate run of the market simulator instance.
* If this property is specified with a value, it will result in deterministic generation of orders that will be unique per listing. This deterministic generation of orders is only guaranteed within the sequence of updates per each listing. Since each listing is managed in a separate thread, overall updates mixed across all listings will still be produced with non-deterministic results.
|===

Start or stop random order generation and historical data playback for the current market simulator venue instance.

_Resource URI_

----
POST /api/[genstart|genstop]
----

Start or stop random order generation and historical data playback for a specific market simulator venue instance.

_Resource URI_

----
POST /api/[genstart|genstop]/{venueId}
----

_Example_: Request to start generation for the current venue

[,http]
----
POST /api/genstart HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost
----

_Example_: Possible reply

[,http]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "result" : "Random orders generator started successfully"
}
----

_Example_: Request to start generation with a static seed

[,http]
----
POST /api/genstart HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost

{
    "seed":"abc"
}
----

_Example_: Possible reply

[,http]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "result" : "Random orders generator started successfully"
}
----

_Example_: Request to start generation for a specific venue

[,http]
----
POST /api/genstart/XETRA HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost
----

_Example_: Possible reply

[,http]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "result" : "Random orders generator started successfully"
}
----

_Example_: Request to stop generation for the current venue

[,http]
----
POST /api/genstop HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost
----

_Example_: Possible reply

[,http]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "result" : "Random orders generator stopped successfully"
}
----

_Example_: Request to stop generation for a specific venue

[,http]
----
POST /api/genstop/XETRA HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost
----

_Example_: Possible reply

[,http]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "result" : "Random orders generator stopped successfully"
}
----

[[admincmds-mktphshalt]]
=== Market Phase Halt
Manage halted status of current market phase of each market simulator venue instance. See <<general-mktphs,this section>> for more information about market phases.

_Response Properties_

[1,1,1]
|===
| Path | Type |Description

| result | Text | Explanation of HTTP code received in response to request
|===

[[admincmds-mktphshalt-haltresume]]
==== Halt/Resume Market Phase
Halt or resume current market phase for a single market simulator venue instance.

_Request Properties_

[cols="25,15,60"]
|===
| Path | Type |Description

| allowCancels | Boolean a| Defines whether order cancellation by OrderCancelRequest (35=F) is allowed during the Open Halted phase. Used only when halting current market phase.

*	`true` - OrderCancelRequest (35=F) can be processed. 
If the order is cancelled, the market simulator's response is ExecutionReport (35=8), in which OrdStatus is Canceled (39=4).
*	`false` - OrderCancelRequest (35=F) will be rejected - orders cannot be cancelled. 
The market simulator's response is OrderCancelReject (35=9), in which OrdStatus is Rejected (39=8).
|===

Halt or resume the current market phase for the current market simulator venue instance.

_Resource URI_

----
POST /api/[halt|resume]
----

Halt or resume current market phase for a specific market simulator venue instance.

_Resource URI_

----
POST /api/[halt|resume]/{venueId}
----

_Example_: Halt market for the current venue

[,http]
----
POST /api/halt HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost

{
    "allowCancels": false
}
----

_Example_: Positive reply

[,http]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "result" : "Market successfully halted"
}
----

_Example_: Reply if the phase is already halted

[,http]
----
HTTP/1.1 409 Conflict
Connection: Close
Content-Length: XXX

{
    "result" : "The market is already halted."
}
----

_Example_: Reply if there is no active phase

[,http]
----
HTTP/1.1 404 Not Found
Connection: Close
Content-Length: XXX

{
    "result" : "There is no phase to halt."
}
----

_Example_: If the current phase cannot be halted

[,http]
----
HTTP/1.1 409 Conflict
Connection: Close
Content-Length: XXX

{
    "result" : "Unable to halt the phase."
}
----

_Example_: Halt market for a specific venue

[,http]
----
POST /api/halt/LSE HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost

{
    "allowCancels": false
}
----

_Example_: Positive reply

[,http]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "result" : "Market successfully halted"
}
----

_Example_: Reply if the phase is already halted

[,http]
----
HTTP/1.1 409 Conflict
Connection: Close
Content-Length: XXX

{
    "result" : "The market is already halted."
}
----

_Example_: Reply if there is no active phase

[,http]
----
HTTP/1.1 404 Not Found
Connection: Close
Content-Length: XXX

{
    "result" : "There is no phase to halt."
}
----

_Example_: If the current phase cannot be halted

[,http]
----
HTTP/1.1 409 Conflict
Connection: Close
Content-Length: XXX

{
    "result" : "Unable to halt the phase."
}
----

_Example_: Resume market for the current venue

[,http]
----
POST /api/resume HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost
----

_Example_: Positive reply

[,http]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "result" : "The market was successfully resumed."
}
----

_Example_: Reply if the phase is not currently halted

[,http]
----
HTTP/1.1 409 Conflict
Connection: Close
Content-Length: XXX

{
    "result" : "There is no halt request to terminate."
}
----

_Example_: Resume market for a specific venue

[,http]
----
POST /api/resume/LSE HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost
----

_Example_: Positive reply

[,http]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "result" : "The market was successfully resumed."
}
----

_Example_: Reply if the phase is not currently halted

[,http]
----
HTTP/1.1 409 Conflict
Connection: Close
Content-Length: XXX

{
    "result" : "There is no halt request to terminate."
}
----

[[admincmds-simstate]]
=== Market Simulator State
Manage the current state of traded market listings and settings for each market simulator venue instance.

_Response Properties_

[1,1,1]
|===
| Path | Type |Description

| result | Text | Explanation of HTTP code received in response to request
|===

[[admincmds-simstate-storerecover]]
==== Store/Recover Market State For Single Venue
Store or recover current market state of traded listings for a single market simulator venue instance with a persisted state file. This includes only the live market state of each traded listing, not the configured settings from the database. See <<general-persiststate,this section>> for more information about persisted market state.

Store or recover market state for current market simulator venue with configured persisted state file.

_Resource URI_

----
POST /api/[store|recover]
----

Store or recover market state for specific market simulator venue with configured persisted state file.

_Resource URI_

----
POST /api/[store|recover]/{venueId}
----

_Example_: Store market state for current venue

[,http]
----
POST /api/store HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost
----

_Example_: Positive reply

[,http]
----
HTTP/1.1 201 Created
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "result": "Matching engine state has been successfully persisted." 
}
----

_Example_: Store market state for a specific venue

[,http]
----
POST /api/store/LSE HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost
----

_Example_: Positive reply

[,http]
----
HTTP/1.1 201 Created
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "result": "Matching engine state has been successfully persisted." 
}
----

_Example_: Recover market state for current venue

[,http]
----
POST /api/recover HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost
----

_Example_: Positive reply

[,http]
----
HTTP/1.1 201 Created
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "result" : "Matching engine state has been successfully recovered"
}
----

_Example_: Recover market state for a specific venue

[,http]
----
POST /api/recover/LSE HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost
----

_Example_: Positive reply

[,http]
----
HTTP/1.1 201 Created
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "result" : "Matching engine state has been successfully recovered"
}
----

[[admincmds-simstate-reset]]
==== Reset Configured State For Single Venue

Reset configured initial state for a single market simulator venue instance from database settings. All simulator settings will be refreshed from the database. If the venue is configured with persistenceEnabled = true, like a normal simulator startup sequence, the listings specified in the configured persistence file path for that venue will have their market state restored, and any other active traded listings will have their market states cleared. Random order generation and historical data playback will also be stopped, and only restarted if the venue is configured with orderOnStartup = true. The REST and FIX engines will also be reset during this time, causing active connections to be disrupted.

The simulator XML file configuration and FIX file configuration will not be reloaded during a reset. A physical restart of the market simulator process is required to reload these settings.

WARNING: Changing the venueId of the venue associated with the simulator instance or the configured restPort for a live running market simulator instance before resetting the configured state is not supported and will likely have unstable results.

Reset configured state for current market simulator venue.

_Resource URI_

----
POST /api/reset
----

Reset configured state for a specific market simulator venue.

_Resource URI_

----
POST /api/reset/{venueId}
----

_Example_: Reset configured state for current venue

[,http]
----
POST /api/reset HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost
----

_Example_: Positive reply

[,http]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "result" : "Resetting the venue state starts."
}
----

_Example_: Reset configured state for a specific venue

[,http]
----
POST /api/reset/LSE HTTP/1.1
Accept: application/json;charset=UTF-8
Host: localhost
----

_Example_: Positive reply

[,http]
----
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Content-Length: XXX

{
    "result" : "Resetting the venue state starts."
}
----
