# .github/workflows/build-liquibase-image.yml
name: Build Liquibase image

on:
  push:
    branches:
      -  main
      -  develop
    paths:
      - 'db/**' 
      - '.github/docker/liquibase_custom.Dockerfile' 
      - '.github/workflows/build-liquibase-image.yml' 
    tags:
      - 'v[0-9]+.[0-9]+'
      - 'v[0-9]+'
  workflow_dispatch: 
    inputs:
      trigger_liquibase: 
        description: 'Set to "liquibase" to force a build (e.g., to rebuild image without code changes)'
        required: false
        default: '' 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions: 
      packages: write 
      contents: read  
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.trigger_liquibase == 'liquibase' || github.event_name == 'push' && github.event.before == '0000000000000000000000000000000000000000' || github.event_name == 'push' && github.event.before != '0000000000000000000000000000000000000000' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set lowercase owner
        run: echo "REPO_OWNER_LOWER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Determine image tags
        run: |
          BASE_IMAGE_NAME="ghcr.io/${REPO_OWNER_LOWER}/liquibase"

          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            SAFE_TAG="${GITHUB_REF_NAME}"
            TAGS="$BASE_IMAGE_NAME:$SAFE_TAG"
          elif [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            TAGS="$BASE_IMAGE_NAME:main,$BASE_IMAGE_NAME:latest"
          elif [[ "${GITHUB_REF_NAME}" == "develop" ]]; then
            TAGS="$BASE_IMAGE_NAME:develop"
          else
            SAFE_TAG="${GITHUB_REF_NAME//\//-}"
            TAGS="$BASE_IMAGE_NAME:$SAFE_TAG"
          fi

          echo "LIQUIBASE_IMAGE_TAGS=$TAGS" >> "$GITHUB_ENV"
          echo "Final image tag(s): $TAGS"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build + push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .github/docker/liquibase_custom.Dockerfile
          push: true
          tags: ${{ env.LIQUIBASE_IMAGE_TAGS }}
